@startuml
title Klassendiagramm: GameOfLife

class GameOfLife {
    - boolean[][] field

    --
    + GameOfLife(boolean[][] field)
    --
    + String show()
    + int population()
    + boolean extinct()
    + static GameOfLife fromString(String m)
    + int anzahlBelegterNachbarn(int x, int y)
    + GameOfLife nextGeneration()
    + void waitAndClear()
    + void play()
    + void playN(int generations)
    + static void main(String... args)

    --
    {static} String ex1
}

@enduml
