@startuml
title Ablauf der play()-Methode

start

:current = this;

repeat
    :waitAndClear();
    :System.out.println( current.show() );

    if ( current.population() == 0 ) then (ja)
        :System.out.println("Alle Zellen sind ausgestorben.");
        stop
    endif

    :current = current.nextGeneration();
repeat while (true)

@enduml
