public class TestMain {

    public static void main(String[] args) {
        testAllPatterns(10, 500);
    }

    static void testAllPatterns(int generations, int pauseMillis) {

        String[] names = {
                "Glider",
                "Gosper Glider Gun",
                "Pulsar",
                "SwitchEngine",
                "Spaceship"
        };

        String[] patterns = {
                Glider,  //Kleines Raumschiff, bewegt sich diagonal
                GosperGliderGun, //Erzeugt unendlich viele Glider
                Pulsar, //Großer Oszillator (Periode 3)
                SwitchEngine, //Unendlicher Wachstums-Motor
                Spaceship //kleines horizontales Raumschiff
        };

        for (int i = 0; i < patterns.length; i++) {
            System.out.println("=== STARTE PATTERN: " + names[i] + " ===");

            GameOfLife.fromString(patterns[i]).playN(generations);

            try {
                Thread.sleep(pauseMillis);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }

            // Bildschirm löschen
            System.out.print("\033[H\033[2J");
            System.out.flush();
        }
    }

    static String Glider = """
            ....................
            ....................
            ....................
            ....................
            ........0...........
            ..........0.........
            .......000..........
            ....................
            ....................
            ....................
            ....................""";

    static String GosperGliderGun = """
            ....................
            ............0.......
            ..........0.0.......
            ........00....00.....
            ........00....00.....
            ........00....00.....
            ..........0.0.......
            ............0.......
            ....................
            ....................
            ....................""";

    static String Pulsar = """
            ....................
            ....................
            ......000.000.......
            ....................
            .....0..0.0..0......
            .....0..0.0..0......
            .....0..0.0..0......
            ....................
            ......000.000.......
            ....................
            ....................""";

    static String SwitchEngine = """
            ....................
            ....................
            .............0......
            ..............0.....
            ............000.....
            ...........0..0.....
            ............0.......
            ....................
            ....................
            ....................
            ....................""";


    static String Spaceship = """
            ....................
            ....................
            ....................
            ............0.......
            ........0.....0.....
            ........0...........
            ........0000........
            ....................
            ....................
            ....................
            ....................
            """;


}
